### ISSUE TITLE
Access to Tweet Metadata?

### ISSUE THREAD

**Issue by KareemAlaa2001** [GabrielHam/TwiBot-20#1]
Hi,

Thanks for releasing this larger and more comprehensive dataset. I was wondering if there was a version that also contains the full property data about the tweets themselves, and if it would be possible to gain access to that as well. 

Thanks

**Comment by BunsenFeng** [comment]
Hi,

To our great regret, we did not store the tweet properties when collecting TwiBot-20. We are fully aware of this issue now and we will provide full property data about tweets in our follow-up work TwiBot-22. Sorry for the inconvenience.

**Comment by KareemAlaa2001** [comment]
Ah that's unfortunate, thank you for the quick response.
